name: flutter_misskey_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  collection: ^1.16.0
  flutter:
    sdk: flutter
  flutter_html: 3.0.0-alpha.6
  flutter_riverpod: ^2.3.2
  misskey_dart:
    path: ../misskey_dart
  mfm_renderer:
    path: ../mfm_renderer
  tuple: ^2.0.1
  path_provider: ^2.0.14
  dio: ^5.1.1
  path: ^1.8.2
  auto_route: ^6.0.5
  freezed_annotation: ^2.2.0
  url_launcher: ^6.1.10
  intl: ^0.18.1
  scrollable_positioned_list: ^0.3.6
  kana_kit: ^2.0.0
  cached_network_image: ^3.2.3
  json_annotation: ^4.8.0
  shared_preferences: ^2.1.0
  badges: ^3.1.1
  flutter_secure_storage: ^8.0.0
  google_fonts: ^4.0.4
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  auto_route_generator: ^6.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true

fonts:
  - family: KosugiMaru
    fonts:
      - asset: assets/fonts/KosugiMaru-Regular.ttf
        weight: 300
      - asset: assets/fonts/KosugiMaru-Regular.ttf
        weight: 400
      - asset: assets/fonts/KosugiMaru-Regular.ttf
        weight: 500
      - asset: assets/fonts/KosugiMaru-Regular.ttf
        weight: 600
